/**
 * "Report an issue" — turn a panel plus a sentence from the user into a
 * markdown report on disk and an iTerm2 window running `claude` in the
 * brainhouse checkout, seeded with that report.
 *
 * Design: `docs/superpowers/specs/2026-08-19-report-issue-design.md`.
 */

import { execFile } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';

const execFileAsync = promisify(execFile);

export function reportsDir(): string {
  return process.env.BRAINHOUSE_REPORTS_DIR ?? path.join(os.homedir(), '.brainhouse', 'reports');
}

/** The brainhouse checkout this server was built from — `<repo>/server/dist`
 * at runtime, `<repo>/server/src` under tsx. Derived rather than configured so
 * a moved checkout can't strand the launcher on a stale path. */
export function brainhouseRoot(): string {
  return path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
}

export interface ReportContext {
  panelId: string;
  kind: string;
  parentPanelId: string | null;
  title: string;
  agentType: string | null;
  accountLabel: string | null;
  status: string;
  cwd: string | null;
  repoRoot: string | null;
  startedAt: number;
  lastEventAt: number;
  transcriptPath: string | null;
  brainhouseRevision: string | null;
}

function iso(epochSeconds: number): string {
  return new Date(epochSeconds * 1000).toISOString();
}

export function renderReport(text: string, ctx: ReportContext): string {
  const rows: [string, string][] = [
    ['Panel id', ctx.panelId],
    ['Kind', ctx.kind],
    ['Parent panel', ctx.parentPanelId ?? '—'],
    ['Title', ctx.title],
    ['Agent type', ctx.agentType ?? '—'],
    ['Account', ctx.accountLabel ?? '—'],
    ['Status', ctx.status],
    ['cwd', ctx.cwd ?? '—'],
    ['Repo root', ctx.repoRoot ?? '—'],
    ['Started', iso(ctx.startedAt)],
    ['Last event', iso(ctx.lastEventAt)],
    ['Transcript', ctx.transcriptPath ?? 'not found on disk'],
    ['brainhouse HEAD', ctx.brainhouseRevision ?? 'unknown'],
  ];
  return [
    '# brainhouse issue report',
    '',
    '## What looks wrong',
    '',
    text.trim(),
    '',
    '## Context',
    '',
    ...rows.map(([k, v]) => `- **${k}:** ${v}`),
    '',
    '## Task',
    '',
    'You are in the brainhouse checkout. Read `CLAUDE.md` and',
    '`docs/assertions.md` before changing anything — assertions.md is the',
    'declarative record of how panels are supposed to behave, and a new rule',
    'belongs there alongside whatever you fix.',
    '',
    'Find the root cause of the behavior described above for that panel.',
    'The transcript path is the raw JSONL the panel was built from; the',
    'view pipeline that shapes it into what gets rendered lives in',
    '`client/src/transforms/` (composed in `transforms/registry.ts`), and',
    'parsing is `server/src/parser.ts`. Report the root cause before',
    'proposing a fix.',
    '',
  ].join('\n');
}

/** Single-quote a value for `/bin/zsh`. */
function shellQuote(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`;
}

export function launchScript(repoRoot: string): string {
  return [
    '#!/bin/zsh',
    '# Regenerated by brainhouse on every report — edits will be overwritten.',
    `cd ${shellQuote(repoRoot)} || exit 1`,
    'claude "$(cat "$1")"',
    '',
  ].join('\n');
}

/** Open an iTerm2 window and run `command` in it once its shell is up.
 *
 * Creating the window with a `command` would replace the login shell with it,
 * so it starts before the profile and shell integration have loaded and
 * `claude` is not yet on PATH. Creating the window bare and typing the command
 * in gives a normal interactive login shell, at the cost of having to wait for
 * one: `is at shell prompt` is the shell-integration signal that it's ready,
 * and installations without it fall back to a fixed settle.
 *
 * The command arrives as argv so nothing is interpolated into AppleScript
 * source — the same discipline `revealItermSession` uses in
 * `processes/native.ts`. */
export const ITERM_LAUNCH_SCRIPT = `on run argv
  set theCommand to item 1 of argv
  tell application "iTerm2"
    set theWindow to (create window with default profile)
    set theSession to current session of theWindow
    set isReady to false
    set hasShellIntegration to true
    repeat 100 times
      if not hasShellIntegration then exit repeat
      try
        if is at shell prompt of theSession then
          set isReady to true
          exit repeat
        end if
      on error
        set hasShellIntegration to false
      end try
      delay 0.1
    end repeat
    if not isReady then delay 1.5
    tell theSession to write text theCommand
    activate
  end tell
  return "ok"
end run`;

/** What gets typed at the prompt. No `zsh -ilc` wrapper — the session iTerm
 * created is already an interactive login shell. */
export function itermCommand(launcherPath: string, reportPath: string): string {
  return `${shellQuote(launcherPath)} ${shellQuote(reportPath)}`;
}

/** Slug a panel id for use in a filename — panel ids are uuids or `a<hex>`
 * agent ids, but nothing downstream guarantees that. */
function safeId(panelId: string): string {
  return panelId.replace(/[^a-zA-Z0-9_-]/g, '_').slice(0, 64);
}

export function reportFileName(panelId: string, now: Date): string {
  return `${now.toISOString().replace(/[:.]/g, '-')}-${safeId(panelId)}.md`;
}

export async function currentRevision(repoRoot: string): Promise<string | null> {
  try {
    const { stdout } = await execFileAsync('git', ['rev-parse', '--short', 'HEAD'], {
      cwd: repoRoot,
      timeout: 5000,
    });
    return stdout.trim() || null;
  } catch {
    return null;
  }
}

export async function writeAndLaunch(
  text: string,
  ctx: ReportContext,
  now: Date = new Date(),
): Promise<{ reportPath: string; launched: boolean; error?: string }> {
  const dir = reportsDir();
  mkdirSync(dir, { recursive: true });
  const reportPath = path.join(dir, reportFileName(ctx.panelId, now));
  writeFileSync(reportPath, renderReport(text, ctx), 'utf8');

  const launcherPath = path.join(dir, 'launch.sh');
  writeFileSync(launcherPath, launchScript(brainhouseRoot()), { encoding: 'utf8', mode: 0o755 });

  if (process.platform !== 'darwin') {
    return { reportPath, launched: false, error: `unsupported platform: ${process.platform}` };
  }
  try {
    const { stdout } = await execFileAsync(
      'osascript',
      ['-e', ITERM_LAUNCH_SCRIPT, itermCommand(launcherPath, reportPath)],
      { timeout: 30000 },
    );
    if (stdout.trim() === 'ok') return { reportPath, launched: true };
    return {
      reportPath,
      launched: false,
      error: `osascript returned ${stdout.trim() || '(empty)'}`,
    };
  } catch (e) {
    // Surfaced rather than swallowed: the usual cause is a missing Automation
    // grant for the server process, which is invisible without the message.
    return { reportPath, launched: false, error: errorText(e) };
  }
}

function errorText(e: unknown): string {
  const err = e as { stderr?: string; code?: unknown; signal?: unknown; killed?: boolean };
  const parts = [
    err?.stderr?.trim(),
    err?.code !== undefined ? `exit=${String(err.code)}` : null,
    err?.signal ? `signal=${String(err.signal)}` : null,
    err?.killed ? 'killed=true' : null,
  ].filter(Boolean);
  if (parts.length) return parts.join(' ');
  return e instanceof Error ? e.message : String(e);
}
